#!/bin/bash
# Fetch, merge, and commit PR to local branch
# Assumes remote is named upstream
# run with  `addpr [pull request number] [commit message]`

readonly REMOTE="upstream"
readonly PR_NUM="$1"
shift
COMMIT_MESSAGE="$*"

git fetch ${REMOTE} pull/${PR_NUM}/head && git merge --squash FETCH_HEAD && git commit -m "$COMMIT_MESSAGE"
