#!/bin/bash
#Fetches changes from remote repo and applies to QA's relevant branches
#Assumes remote branch is named upstream

REMOTE="upstream"
CURRENT_DIR=${PWD##*/}

if [[ ! -d ./.git ]]; then
  echo "error: Current directory is not a git repository" >&2; exit 1
fi

if [[ $CURRENT_DIR = "SharpSpringNG" ]]; then
  declare -a branches=("master" "staging" "staging-new")
else
  declare -a branches=("master" "staging")
fi

for branch in "${branches[@]}"
do
  git checkout ${branch}
  git fetch ${REMOTE} ${branch}
  git reset --hard ${REMOTE}/${branch}
done