#!/bin/bash

# Fetches all new changes from remote repo and applies to QA's relevant branches
#Assumes remote branch is named upstream

REMOTE="upstream"
CURRENT_DIR=${PWD##*/}

git fetch --all

if [[ $CURRENT_DIR = "SharpSpringNG" ]]; then
  declare -a branches=("master" "staging" "staging-new")
else
  declare -a branches=("master" "staging")
fi

for branch in "${branches[@]}"
do
  git checkout ${branch}
  git reset --hard ${REMOTE}/${branch}
done